include:
  - local: .ci/Terraform.gitlab-ci.yml

stages:
  - validate
  - plan
  - deploy

fmt:
  extends: .terraform:fmt
  needs: []

tf_sec:
  extends: .terraform:security
  needs: []

tf plan for YOUR_ACCOUNT_ID:
  extends:
    - .terraform:tf_plan
  variables:
    AWS_ACCOUNT: $YOUR_ACCOUNT_ID
    AWS_ACCESS_KEY_ID: $${YOUR_ACCOUNT_ID}_ACCESS_KEY_ID
    AWS_SECRET_KEY: $${YOUR_ACCOUNT_ID}_SECRET_KEY
  only:
    changes:
      - Terraform/vars/YOUR_ACCOUNT_ID.tfvars

tf_apply:
  extends: .terraform:tf_apply

